name: Build and Run .NET Console App

on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: List directory
        run: ls -R 

      - name: Restore dependencies
        run: dotnet restore ./actions/console-app
      
      - name: Build .NET APP
        run: dotnet build ./actions/console-app --configuration Release
      
      - name: Run .NET APP
        run: dotnet run ./actions/console-app